apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: Y2ZjY2ZkMDg2MzBmZGYwYjMwNWFlZmU4OTllMDBkYjIwMTY2OWI3NGJhN2JkYjNhYjAxMzFhZTQ0MGNhOTZiNGI5MzE2Zjc0YWE0MjE2MDhjYjJjZmZkOWUwZWE0YzBmOTJmN2E2MzU2YzAwNzI3ZTQxZjhlNTMyNDM4YTMyYzkwYjRlOTQ5NzU2NjgzMzQ2ODE2NDgwN2I0NzA1ODQwNmE4MTgwNWE1MjU1YzNiYjI4OTZkN2IyZThkMzI0MDY2NmYzMDU5OWE5ZDI3NWZlYTMyN2IzMmMzNzc4M2M5MTgwZjkxN2UzMzZlNTUzYjk1ZTFmZTQ4MjNhMmI1NWJhZjgwMDU0Mzg2NDNmMzUyMWNjYjE1ZWJhYmQ2ODIyNDYzNzE3MjAxZjM4OGFjZDZkNzYyZjRiYTE4MTJlY2MyYjM3MGQwODhiYzQ3Y2U0NGUxNzYwZTYzNjk0ZmVjZmE0M2JlNTNkZDY2MTdhNWE3ZDk5ZmNjNGZhN2FkMTQ1YmM3MGMxMDRkM2ZjZWM4OTcyMzhiNDFiMmI5ZWNjN2U2ZDcyNWYzM2E5MmIyZDhkMDIwYmE1ZjVhZDQ4OTRmMmZhY2QyM2QxOWIxMmRlNWMwODM3YTA4N2U2YmEwMmY2YzRiZTBiYjRkNTEwODM4MGZiYmZkN2ZhZTNlNmZhNTExYzA=
